version: "3"
services:

  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION:-8.1}
        - XDEBUG=${XDEBUG:-0}
    volumes:
      - ./:/docker
    links:
      - mock

  mock:
    image: telnyx/telnyx-mock:latest
    ports:
      - "12111:12111"
      - "12112:12112"
